/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Stinglez' at '5/06/16 03:14 PM' with Gradle 2.13
 *
 * @author Stinglez, @date 5/06/16 03:14 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
